### ISSUE TITLE
CORS error from browser requests

### ISSUE THREAD

**Issue by Helical-x** [jinaga/jinaga-replicator#9]
Access-Control-Allow-Origin header isn't returned from jinaga-server handler
<img width="672" alt="image" src="https://github.com/user-attachments/assets/e230983e-6f8a-4cbd-acb5-3ad8aa745c67">

Revert this commit:

https://github.com/jinaga/jinaga-replicator/commit/e9341307362f87815e2cf6defbe78d02ed6c044e

pull:
https://github.com/jinaga/jinaga-replicator/pull/10

**Comment by michaellperry** [comment]
Verified fixed in version 3.0.1.
